arch: 
  - amd64
  - ppc64le

script:
  #- sudo pkg install -r FreeBSD shells/bash devel/cmake devel/ninja devel/ccache lang/mono lang/python3 devel/boost-libs devel/libeio security/openssl
  - mkdir .build && cd .build
  - cmake -G Ninja - DUSE_CCACHE=on DDISABLE_TLS=off DUSE_DTRACE=off 
  - ..ninja -j 10
  # run fast tests
  - ctest -L fast
  # run all tests
  - ctest --output-on-failure -v
